# Generated by Django 6.0 on 2026-01-14 11:25

import topcomputersapp.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(storage=topcomputersapp.storages.ProductStorage(), upload_to='')),
                ('file_size_mb', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('file_type', models.CharField(editable=False, max_length=100)),
                ('file_extension', models.CharField(editable=False, max_length=10)),
                ('is_image', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
