# Generated by Django 6.0 on 2026-01-23 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topcomputersapp', '0002_contact_storedfile_liked_by_storedfile_likes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='topcomputersapp.filecomment'),
        ),
    ]
